DotnetMVC/WebMVC/Models/LoanInventoryViewModel.cs
namespace WebMVC.Models
{
    public class LoanInventoryViewModel
    {
        public int Id { get; set; }
        public String NameUser { get; set; }
        public String Admin { get; set; }
        public String Detail { get; set; }
        public Boolean Status { get; set; }
        public DateTime Date { get; set; }
        
        public LoanInventoryViewModel()
        {
        }

        public LoanInventoryViewModel(int id, string nameUser, string admin, string detail, bool status, DateTime date)
        {
            Id = id;
            NameUser = nameUser;
            Admin = admin;
            Detail = detail;
            Status = status;
            Date = date;
        }
    }
}

DotnetMVC/WebMVC/Controllers/LoanInventoryController.cs
using Microsoft.AspNetCore.Mvc;
using WebMVC.Models;

namespace WebMVC.Controllers
{
    //int id, string nameUser, string admin, string detail, bool status, DateTime date
    public class LoanInventoryController : Controller
    {
        private static List<LoanInventoryViewModel> _loanInventoryViewModels = new List<LoanInventoryViewModel>()
        {
            new LoanInventoryViewModel(1, "Addyani", "Admin Rapidtech", "Pinjam Laptop Asus Seri X", true, DateTime.Now),
            new LoanInventoryViewModel(2, "Amirul" , "Admin Rapidtech", "Pinjam Laptop MSI Seri X", true, DateTime.Now),
            new LoanInventoryViewModel(3, "Fajar"  , "Admin Rapidtech", "Pinjam Laptop HP Seri X", true, DateTime.Now),
        };

        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Add()
        {
            return View();
        }

        [HttpPost]
        public IActionResult Save([Bind("Id, NameUser, Detail, Admin, Status")] LoanInventoryViewModel loanInventory)
        {
            loanInventory.Date = DateTime.Now;
            _loanInventoryViewModels.Add(loanInventory);
            return Redirect("List");
        }

        public IActionResult List()
        {
            return View(_loanInventoryViewModels);
        }

        public IActionResult Edit(int? id)
        {
            LoanInventoryViewModel loanInventory = _loanInventoryViewModels.Find(x => x.Id.Equals(id));
            return View(loanInventory);
        }

        [HttpPost]
        public IActionResult Update(int id, [Bind("Id, NameUser, Detail, Admin, Status")] LoanInventoryViewModel loanInventory)
        {
            LoanInventoryViewModel loanInventoryOld = _loanInventoryViewModels.Find(x => x.Id.Equals(id));
            _loanInventoryViewModels.Remove(loanInventoryOld);

            loanInventory.Date = DateTime.Now;
            _loanInventoryViewModels.Add(loanInventory);
            return Redirect("List");
        }

        public IActionResult Details(int id)
        {
            LoanInventoryViewModel loanInventory = (
                    from p in _loanInventoryViewModels
                    where p.Id.Equals(id)
                    select p
                ).SingleOrDefault(new LoanInventoryViewModel());
            return View(loanInventory);
        }

        public IActionResult Delete(int? id)
        {
            LoanInventoryViewModel loanInventory = _loanInventoryViewModels.Find(x => x.Id.Equals(id));
            _loanInventoryViewModels.Remove(loanInventory);

            return Redirect("/LoanInventory/List");
        }
    }
}

DotnetMVC/WebMVC/Views/LoanInventory/Add.cshtml
@model LoanInventoryViewModel
@{
    ViewData["Title"] = "LoanInventory View Data";
}

<h2>Form Add Loan Inventory</h2>

<form asp-action="Save" method="post">
    <div class="form-group">
        <label asp-for="Id">Loan Inventory Id</label>
        <input asp-for="Id" class="form-control">
    </div>
    
    <div class="form-group">
        <label asp-for="NameUser">Name User For Loan</label>
        <input asp-for="NameUser" class="form-control">
    </div>

    <div class="form-group">
        <label asp-for="Detail">Detail</label>
        <input asp-for="Detail" class="form-control">
    </div>

    <div class="form-group">
        <label asp-for="Admin">Admin Pemberi Acc</label>
        <input asp-for="Admin" class="form-control">
    </div>

    <div class="form-group">
        <label asp-for="Status">Status Peminjaman</label>
        <select class="form-select" aria-label="Set Status" id="Status" name="Status"> 
            <option selected>Select Status Here</option>
            <option value="false">False</option>
            <option value="true">True</option>
        </select>
    </div>


    <button type="submit" class="btn btn-primary">Submit</button>
</form>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

DotnetMVC/WebMVC/Views/LoanInventory/Details.cshtml
@model LoanInventoryViewModel

@{
    ViewData["Title"] = "Product Details";
}

<h2>Product Detail</h2>
<table class="table tab-content">
    <tbody>
        <tr>
            <th>ID</th>
            <td>@Model.Id</td>
        </tr>
        <tr>
            <th>User Name</th>
            <td>@Model.NameUser</td>
        </tr>
        <tr>
            <th>Detail</th>
            <td>@Model.Detail</td>
        </tr>
        <tr>
            <th>Detail</th>
            <td>@Model.Admin</td>
        </tr>
        <tr>
            <th>Detail</th>
            <td>@Model.Status</td>
        </tr>
        <tr>
            <th>Date</th>
            <td>@Model.Date</td>
        </tr>

    </tbody>
</table>

<a class="btn btn-sm btn-primary" asp-area="" asp-controller="LoanInventory" asp-action="List">Back</a>

DotnetMVC/WebMVC/Views/LoanInventory/Edit.cshtml
@model LoanInventoryViewModel
@{
    ViewData["Title"] = "Product Edit Data";
}

<h2>Form Edit Product</h2>

<form asp-action="Update" method="post">
    <div class="form-group">
        <label asp-for="Id">Product Id</label>
        <input asp-for="Id" class="form-control">
    </div>

    <div class="form-group">
        <label asp-for="NameUser">Name User For Loan</label>
        <input asp-for="NameUser" class="form-control">
    </div>

    <div class="form-group">
        <label asp-for="Detail">Detail</label>
        <input asp-for="Detail" class="form-control">
    </div>

    <div class="form-group">
        <label asp-for="Admin">Admin Pemberi Acc</label>
        <input asp-for="Admin" class="form-control">
    </div>

    <div class="form-group">
        <label asp-for="Status">Status Peminjaman</label>
        <select class="form-select" aria-label="Set Status" id="Status" name="Status">
            <option selected>Select Status Here</option>
            <option value="false">False</option>
            <option value="true">True</option>
        </select>
    </div>

    <button type="submit" class="btn btn-primary">Submit</button>
</form>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

DotnetMVC/WebMVC/Views/LoanInventory/Index.cshtml
@{
    ViewData["Title"] = "Loan Inventory - Index";
}

<div class="text-center">
    <h1 class="display-4">Loan Inventory Index</h1>
    <p>Learn about <a href="https://docs.microsoft.com/aspnet/core">building Web apps with ASP.NET Core</a>.</p>
</div>

DotnetMVC/WebMVC/Views/LoanInventory/List.cshtml
@model List<LoanInventoryViewModel>
@{
    ViewData["Title"] = "Loan Inventory List";
}

<h2>Loan Inventory List</h2>
<a class="btn btn-sm btn-primary" asp-area="" asp-controller="LoanInventory" asp-action="Add">Create New Loan</a>

<table class="table table-responsive">
    <thead>
    <tr>
        <th>ID</th>
        <th>NameUser</th>
        <th>Detail</th>
        <th>Admin</th>
        <th>Date</th>
        <th>Status</th>
    </tr>
    </thead>
    <tbody>
    @foreach(var item in Model )
    {
        <tr>
            <td>@item.Id</td>
            <td>@item.NameUser</td>
            <td>@item.Detail</td>
            <td>@item.Admin</td>
            <td>@item.Date</td>
            <td>@item.Status</td>
            <td>
                <a asp-action="Edit" asp-route-id="@item.Id" class="btn btn-sm btn-warning">Edit</a>
                <a asp-action="Details" asp-route-id="@item.Id" class="btn btn-sm btn-success">View</a>
                <a asp-action="Delete" asp-route-id="@item.Id" class="btn btn-sm btn-danger">Delete</a>
            </td>
        </tr>
    }
    </tbody>
</table>